apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: santospedia-manutencao-ingress
  namespace: santospedia
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  tls:
    - hosts:
        - santospedia.com.br
      secretName: santospedia-tls
  rules:
    - host: santospedia.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: santospedia-manutencao-svc
                port:
                  number: 80